### ISSUE TITLE
Logs are getting alphabetically sorted

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1021]
**Describe the bug**

When logging multiple times, the logs are getting sorted and repeated same logs are dropped.

**To Reproduce**

Run in REPL:
```Haskell
log "a"; log "b"; log "c"; log "d"; log "e"
log "e"; log "d"; log "c"; log "b"; log "a"
log "z"; log "z"; log "z"; log "z"; log "z"
```

**Expected behaviour**

I wanted to see "abcde", "edcba" and "zzzzz".

**Screenshots**
![image](https://user-images.githubusercontent.com/44544735/213879013-f2b4f136-ac1b-4a66-9da4-55381e4894e9.png)

**Comment by xsebek** [comment]
Web API to the rescue! The messages are stored correctly, _except they have the same time!_
```bash
curl http://localhost:5357/robot/0 | yq -P '._robotLog' | grep -Ei 'text|time'
```
```YAML
  _leText: z
  _leTime: 50
  _leText: z
  _leTime: 50
  _leText: z
  _leTime: 50
  _leText: z
  _leTime: 50
  _leText: z
  _leTime: 50
```
