### ISSUE TITLE
World function DSL

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#1320]
**Is your feature request related to a problem? Please describe.**

The world function is currently static except for _seed_. Being able to parametrise it would be helpful in several places:
1. in custom scenarios
2. in scenario launch options (#1290)
3. in save files (#50)
4. in world editor? (#873)

Another related problem is that we currently have competing ways to specify the world.
Namely specifying the seed, default entity and a part of map.
When the default entity is specified, it will disregard the seed and default world function.

**Describe the solution you'd like**
We should create a simple configuration scheme, that we can play with, modify and extend.

In YAML the current world function could look like this:
```yaml
world:
  parameters:
    noise: # WorldGen.hs: Perlin noises p0, p1, p2, cl0
      smallBig: [0, 6, 0.05, 0.6]  # seed, number of octaves, scale, and persistance.
      softHard: [1, 6, 0.05, 0.6]  # we could specify those as object parameters or tuple
      naturalArtificial: [2, 6, 0.05, 0.6]  # here I am using tuple to be brief, but object is likely better
      choice: [0, 4, 0.08, 0.5]
    biomes:
      big:
        hard:
          natural:  # WorldGen.hs: genBiome Big Hard Natural
            # use object for conditions
            - [{sample: 0.5}, "stone", "mountain"]
            # interpret top-down
            - [{murmur: {mod: 30, equal: 0}}, "stone", "boulder"]
            # combine conditions
            - [{sample: 0.5; murmur: {mod: 30, equal: 0}}, "stone", "LaTeX"]
            - [{sample: 0.5}, "stone", "tree"] 
            # use otherwise string like in Haskell and null for no entity
            - [otherwise, "grass", null]
          artificial:
             # ...
      small:
        # ...
```

The Haskell datatype `WorldParameters` would follow this structure and get interpreted like `testWorld2`.

**Describe alternatives you've considered**

In general (ignoring the specific syntax proposed here) the only alternative is passing parameters ad-hoc in code.
That is fine for current seed and default entity, but will need more structured approach later.

**Additional context**

- We should consider how changes to the scheme will impact saves.
  Adding a new field should not brick all player save files... at least once we have a stable release. 😄 
- We should measure the performance impact.
  A new benchmark would be needed.
