### ISSUE TITLE
Robot inventory limits

### ISSUE THREAD

**Issue by kostmo** [swarm-game/swarm#1643]
In a robot definition within a scenario file, a new property `capacity` may be added to limit the quantity of a certain entities allowed in the inventory.

For backward compatibility and by default, any entity not listed explicitly in the `capacity` list would support unlimited quantity in the inventory.

As an example, we may have:
```
robots:
  - name: base
    dir: [0, 1]
    capacity:
      - [50, alfalfa]
      - [5, bales]
    inventory:
      - [5, fence]
      ...
```
A scenario may entail harvesting `alfalfa`.  When alfalfa capacity is reached, one must craft a `bale` to make more room in inventory, and lay down a `bale` in the field when 5 are accumulated.  The scenario may go on to have bales distributed to cattle as feed...
