### ISSUE TITLE
Minimize size of generated JSON for `CESK`

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1907]
As an experiment towards #50 (see also #347), I started up a creative scenario, loaded some code from a `.sw` file, ran a base program, and then serialized a snapshot of the base's CESK machine to a file.  Unfortunately it was almost 3MB in size!  However, most of it was unnecessary junk such as empty comments records.  If we want saving games to be practical we will need to work a lot harder to minimize the size of generated JSON.

As one simple example, if a `Comments` record is empty we should be able to omit it entirely from the output.  I'm sure there is lots more similar low-hanging fruit.

**Comment by byorgey** [comment]
I suspect there is a lot of bloat from multiple closures containing `Env`s that contain duplicate bindings.  In memory, there is a lot of sharing going on, but we lose the sharing when we serialize.

**Comment by byorgey** [comment]
Another bit of low-hanging fruit is to make custom instances for `Type` and `Term/Syntax` where `ToJSON` pretty-prints to a string and `FromJSON` runs the parser.

**Comment by xsebek** [comment]
@byorgey, how about splitting low-hanging fruits from this one? 🙂

**Comment by byorgey** [comment]
> @byorgey, how about splitting low-hanging fruits from this one? 🙂

Well, to be honest, I'm not sure what they are.  I already addressed the one example I mentioned.

**Comment by xsebek** [comment]
@byorgey we could split off some improvements (numbers are for Blank scenario base):

* empty comments:
  ```yaml
  _sComments:
    _afterComments: []
    _beforeComments: []
  ```
* empty location:
  ```yaml
  _sLoc: NoLoc
  ```
* capabilities include the _complete description of the entity_ that provides it _repeatedly_ (8x calculators):
    ```yaml
    - - charat
      - - device:
            capabilities:
              getMap:
                - - charat
                  - ingredients: []
                - - tochar
                  - ingredients: []
            description: |-
              A handy lookup table for converting from characters to numeric codes and back, shaped for some reason into a ring.  When equipped, it enables two functions:

              `charat : Int -> Text -> Int` returns the numeric code of the character at a specific index in a (0-indexed) `Text` value.

              `tochar : Int -> Text` creates a singleton (length-1) `Text` value containing a character with the given numeric code.
            display:
              attr: silver
              char: O
              priority: 1
            name: decoder ring
            properties:
              - pickable
            tags: []
          useCost:
            ingredients: []
    ```
* empty ingredients (399x):
  ```yaml
  capabilities:
    getMap:
      - - neg
        - ingredients: []
  ```
* empty tags (111x):
  ```yaml
  tags: []
  ```
* default priority (111x):
  ```
  priority: 1
  ```
