### ISSUE TITLE
Snippets get printed on multiple lines

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#1910]
See the screenshot and discussion at https://github.com/swarm-game/swarm/pull/1906#discussion_r1629906059 .

**Comment by nitinprakash96** [comment]
To add some more context the the issue, this happens when snippets are defined with line breaks in `entities.yaml`. Eg:

(Renders with newline)
```yaml
- name: Elmer's glue
  description:
  - | 
    The infix operator `++ : Text -> Text ->
    Text`{=snippet} can be used to concatenate two `Text`{=type} values.  For example,
```

(Renders without newline)
```yaml
- name: Elmer's glue
  description:
    - |
      The infix operator `++ : Text -> Text -> Text`{=snippet}
      can be used to concatenate two `Text`{=type} values.  For example,
```

This is possibly because of how snippets are treated in printing context:
https://github.com/swarm-game/swarm/blob/0eca3154009b8f5078b5c4b1da393f615236acf3/src/swarm-lang/Swarm/Language/Text/Markdown.hs#L327
