### ISSUE TITLE
Inconsistent best and last times

### ISSUE THREAD

**Issue by noahyor** [swarm-game/swarm#1932]
The best and last times are different after completing a scenario once.

These times should be the same.

![Screenshot (8)](https://github.com/swarm-game/swarm/assets/66531214/8747308a-a52f-4c5d-a083-5050cbde089c)

**Comment by byorgey** [comment]
@kostmo am I remembered correctly that you were the one who added the tracking of best times etc.?  Any ideas off the top of your head why the two listed times for "best" and "last" would be different?

**Comment by xsebek** [comment]
The time in ticks is the same, though. I guess this is caused by the "best time" being fetched before the "last time," but I don't know who updated it last. 🤔 

@noahyor could you please find this scenario in `~/.local/share/swarm/saves` and attach it here?

**Comment by xsebek** [comment]
Actually, I can reproduce it too, so no need to bother you @noahyor. 😅 

Looking inside the file, there are actually multiple metrics and one of them has longer time:
<details>
  <summary>Show file.</summary>

```yaml
path: Tutorials/backstory.yaml
status:
  contents:
  - initialCode: null
    seedVal: null
  - - Completed
    - attemptmetrics:
        codemetrics: null
        durationmetrics:
          elapsed: 41.218964
          elapsedticks: 584
      started: 2024-06-16T18:28:26.47248+02:00
  - bestbyastsize:
    - Completed
    - attemptmetrics:
        codemetrics: null
        durationmetrics:
          elapsed: 37.545951
          elapsedticks: 584
      started: 2024-06-16T18:28:26.47248+02:00
    bestbycharcount:
    - Completed
    - attemptmetrics:
        codemetrics: null
        durationmetrics:
          elapsed: 37.545951
          elapsedticks: 584
      started: 2024-06-16T18:28:26.47248+02:00
    bestbyticks:
    - Completed
    - attemptmetrics:
        codemetrics: null
        durationmetrics:
          elapsed: 37.545951
          elapsedticks: 584
      started: 2024-06-16T18:28:26.47248+02:00
    bestbytime:
    - Completed
    - attemptmetrics:
        codemetrics: null
        durationmetrics:
          elapsed: 37.545951
          elapsedticks: 584
      started: 2024-06-16T18:28:26.47248+02:00
  tag: Played
```

</details>

Which in code corresponds to `ScenarioInfo.scenarioStatus.Played` [second field `ProgressMetric`](https://github.com/swarm-game/swarm/blob/101b17c882918dcabaa2ecad68444c3d15735b1d/src/swarm-engine/Swarm/Game/Scenario/Status.hs#L59).
