### ISSUE TITLE
Running a Swarm script from command line does not load definitions

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#2182]
**Describe the bug**

Running a Swarm script from the command line does not add the definitions to the environment.

**To Reproduce**

* run:
  ```sh
  cabal run swarm -O0 -- --scenario Blank --debug=all --run example/maybe.sw
  ```
* use one of the definitions:
  ```
  > just
  1:1: Unbound variable just
  ```
* there is also nothing in robot environment:
  ```sh
   curl -s localhost:5357/robot/0 | yq -P '.program'
   ```
  ```YAML
  Out:
    - VUnit: []
    - mu: []
      next: 0
    - []
  ```

**Expected behavior**

The player should be able to use the definitions from the run file.
