### ISSUE TITLE
Defining custom entities with the same name as an existing built-in entity has no effect

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#2239]
**Describe the bug**
If in a scenario description you define a custom entity whose name is the same as the name of a standard built-in entity, the custom entity definition has no effect.  Referring to that name will continue to reference the built-in entity.

**To Reproduce**

```
version: 1
name: Custom entity
description: |
  Custom entity overriding standard entity
creative: false
entities:
  - name: rock
    display:
      char: '$'
      attr: gold
    description:
      - Not your average rock!
robots:
  - name: base
    dir: east
    devices:
      - scanner
known: [rock]
world:
  dsl: |
    {grass}
  palette:
    'B': [grass, null, base]
    '$': [grass, rock]
  upperleft: [0, 0]
  map: |
    B$
```

Load the above scenario, `scan forward`, and then view the `rock` in your Compendium.  It is a standard, grey rock displayed with `o` and the standard description.

**Expected behavior**
The only sensible behaviors I can see would be to either
1. allow custom entities to override existing standard entities, OR
2. yield an error and refuse to validate the scenario.

Preferably (1).  Silently ignoring the custom entity seems like a bad default.

**Screenshots**

![2024-12-27-195021_956x348_scrot](https://github.com/user-attachments/assets/395b21c1-95d8-40f3-9c85-ccc7f3ddf89f)
