### ISSUE TITLE
Overridden standard entities are still suggested as a means to provide a missing capability

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#2240]
**Describe the bug**
If a standard entity has been overridden by a custom entity with the same name, the standard entity will still be suggested if it could provide a missing capability, even if the custom entity does not provide that capability.

**To Reproduce**

Once #2241 is merged, load this scenario:

```
version: 1
name: Overridden entity capabilities
description: |
  Overridden standard entity should not still be suggested for its
  capabilities. The error message should suggest "- tank treads", not
  "- treads or tank treads".
creative: false
entities:
  - name: treads
    display:
      char: '#'
      attr: red
    description:
      - Broken treads
    properties: [known, pickable]
robots:
  - name: base
    dir: east
    devices:
      - logger
      - treads
solution: |
  move
world:
  dsl: |
    {grass}
  palette:
    'B': [grass, null, base]
  upperleft: [0, 0]
  map: |
    B
```

Then try to execute `move`.  The following error message is displayed:
```
You do not have the device required for:
  'move'
  Please equip:
  - treads or tank treads
```
Note that it is correct that we get an error message: even though `treads` are equipped, it is a custom entity that does not provide the `move` capability.  The problem is that `treads` are still suggested in the error message.

**Expected behavior**
The error message should mention only `tank treads` as a possibility for providing the `move` capability.

**Additional context**
Note that this depends on fixing #2239 first, i.e. #2241.

I believe the problem lies in the `Semigroup` instance for `EntityMap`.  If any entities are overridden, they must be appropriately removed from the map in the `entitiesByCap` field.
