### ISSUE TITLE
`instant` seems to have no effect when wrapped around definitions

### ISSUE THREAD

**Issue by byorgey** [swarm-game/swarm#2270]
**Describe the bug**
`instant`, when wrapped around a term that includes some expensive `def`s, seems to have no effect.

**To Reproduce**
In the below scenario, the judge does an expensive computation (naive `fib 10`), then places a `rock`. The base robot just executes `move; grab`.  Since the entire judge program is wrapped in `instant`, this ought to work: the entire judge program including the expensive computation and the `place` command should all execute in a single tick, placing the `rock` in time for the `base` to `grab` it.  However, the base crashes with a "nothing here to grab" error, and the rock shows up later.

```
version: 1
name: Instant wrapped defs
description: |
  `instant` should work when wrapped around definitions
creative: false
objectives:
  - goal:
      - Grab the rock
    condition: |
      as base { has "rock" }
robots:
  - name: base
    dir: east
    devices:
      - logger
      - treads
      - grabber
  - name: judge
    dir: east
    system: true
    program: |
      instant (
      def fib : Int -> Int = \n.
        if (n <= 1) {n} {fib (n-1) + fib (n-2)}
      end

      def x = fib 10 end

      create "rock"; place "rock"
      )
solution: |
  move; grab
known: [rock]
world:
  dsl: |
    {grass}
  palette:
    'B': [grass, null, base]
    'j': [grass, null, judge]
  upperleft: [0, 0]
  map: |
    Bj
```

**Additional context**
Ran into this while preparing #2260.  See the discussion here: https://github.com/swarm-game/swarm/pull/2260#discussion_r1903359926
