### ISSUE TITLE
Add localisation

### ISSUE THREAD

**Issue by Nuxssss** [swarm-game/swarm#244]
It would be really great if the game was translated into other languages

**Comment by byorgey** [comment]
While I still think this would be great in theory, https://github.com/swarm-game/swarm/pull/251 nicely illustrates a big practical issue with doing this while the game is still changing a bunch: we would likely get some enthusiastic contributions which would then never be updated, leading to a bunch of out-of-date translations.  I think we need to wait at least until we start making real releases.  Then one of the tasks when doing a release is to make sure the translations are up to date (or drop any that are not).

**Comment by byorgey** [comment]
Note, we now also have things like `goal` which contains a list of strings rather than just a string.  However, I think the same principle would still apply, i.e. `goal` becomes a map from language keys to lists of strings.

```
goal:
  en:
    - Do something.
    - This is another paragraph.
  de:
    - Tun Sie etwas.
    - Dies ist ein weiterer Absatz.
```
