### ISSUE TITLE
Add a simpler way to make default entites known

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#387]
There is a hacky way to make some entity known with a `known` property, but it needs an extra entity:
```yaml
  - name: knownwater
    display:
      attr: water
      char: ' '
    description:
    - An infinite ocean of water.
    properties: [known, portable, growable, liquid]
    growth: [0,0]
```

This results in a lot of copy-pasting and would eventually be pain to keep up to date.

### A simple field

Add a `known` field to scenario taking a list of entities.

### Hiding 0 (or less) entities

Just add the entity to inventory with a zero count and hide it.

Problem is, this is useful for letting the player know what to look for ("find lambda, you currently have 0") and adding other entites would be confusing.

We could hack it with -1 number of entities and always hide <0, but that sounds awful.

### DSL

Allow modifying default entities based on parameters.

```yaml
modify:
  - op: add
    properties: [known]
    entities: [water, wavywater]
```

Possible other use cases:
- add some description to entities in that scenario
- add unwalkable property and change attr to fire to make the floor lava
