### ISSUE TITLE
Scenario entites are not considered for install

### ISSUE THREAD

**Issue by xsebek** [swarm-game/swarm#509]
When a scenario-only entity (like `Tardis`) provides a capability (like `teleport`) it should be installed when building a robot that requires it. But it does not happen.

```Yaml
robots:
  - name: base
    loc: [0,0]
    dir: [1,0]
    devices:
      - logger
      - 3D printer
    inventory:
      - [1, mirror]
      - [1, Tardis]
      - [1, logger]
entities:
  - name: Tardis
    display:
      attr: water
      char: '█'
    description:
    - Bigger on the inside.
    properties: [known, portable]
    capabilities: [senseloc, teleport]
```
```
build {log "Hi, I can teleport!"; teleport self (5,0)}
```

![Screenshot from 2022-06-30 15-45-32](https://user-images.githubusercontent.com/44544735/176693298-22928fbf-1ee6-49d1-b2a7-69f0b9525d65.png)
